# Generated by Django 3.1.5 on 2021-01-20 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.TextField()),
                ('price', models.IntegerField()),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.TextField(max_length=2)),
                ('postal_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gifts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gifts')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subscription')),
            ],
        ),
    ]
